//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class up_11Entities : DbContext
    {
        public up_11Entities()
            : base("name=up_11Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<ReadingList> ReadingLists { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<RoleRequest> RoleRequest { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UnfreezeRequest> UnfreezeRequest { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
